services:
  postgres:
    image: postgres:latest
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketmaster_local

  redis:
    image: redis
    ports:
      - 6379:6379