CREATE TABLE city (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    country_id INT NOT NULL REFERENCES country(id)
);

INSERT INTO city (name, country_id) VALUES
('New York', 1),
('Los Angeles', 1),
('Greater Cairo', 2),
('North Coast', 2);