CREATE TABLE venue (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    city_id INT NOT NULL REFERENCES city(id)
);

INSERT INTO venue (name, city_id) VALUES
('Madison Square Garden', 1),
('Staples Center', 2),
('Cairo International Stadium', 3),
('North Coast Beach Resort', 4);