CREATE TABLE performer (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO performer (name) VALUES
('Taylor Swift'),
('Adele'),
('Beyoncé'),
('Shakira'),
('Amr Diab'),
('Elissa'),
('Nancy Ajram'),
('Tamer Hosny'),
('Mohamed Mounir');