CREATE TABLE event (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    performer_id INT NOT NULL REFERENCES performer(id),
    description VARCHAR(1024),
    venue_id INT NOT NULL REFERENCES venue(id),
    start_time TIMESTAMP NOT NULL
);

INSERT INTO event (name,image_url, performer_id, description, venue_id, start_time) VALUES
(
    'Taylor Swift Concert',
    'https://filmartgallery.com/cdn/shop/files/Taylor-Swift-The-Eras-Tour-Vintage-Movie-Poster-Original_db2242ae.jpg?v=1741760572',
    1,
    'A night of unforgettable music with Taylor Swift.',
    1,
    '2025-10-01 20:00:00'
),
(
    'Adele Live',
    'https://preview.redd.it/official-poster-for-adeles-extended-weekends-with-adele-las-v0-47nglbl0t4qa1.jpg?width=1080&crop=smart&auto=webp&s=8e69ae803776b3de5a47531e2f00c200f4b086b5',
    2,
    'Experience the soulful voice of Adele live in concert.',
    2,
    '2025-10-05 19:30:00'
),
(
    'Beyoncé Homecoming',
    'https://i.pinimg.com/736x/80/a0/f5/80a0f53390de4863bf8dd64717a1879d.jpg',
    3,
    'Beyoncé returns to the stage with a spectacular show.',
    2,
    '2025-10-15 20:30:00'
),
(
    'Shakira Unplugged',
    'https://i.pinimg.com/736x/e1/48/68/e14868c29e5ac537662549c8c9dd0d08.jpg',
    4,
    'An intimate evening with Shakira.',
    3,
    '2025-10-20 18:00:00'
),
(
    'Amr Diab Hits Night',
    'https://amrdiab.net/wp-content/uploads/2022/01/Dubai2022.jpg',
    5,
    'Enjoy a night of classic hits with Amr Diab.',
    4,
    '2025-10-25 19:00:00'
),
(
    'Elissa Acoustic Session',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT48FAgYeRdk8SlqUEmBgZVTGP8uB6ej33fvQ&s',
    6,
    'A special acoustic session with Elissa.',
    3,
    '2025-10-30 17:30:00'
),
(
    'Nancy Ajram Live in Cairo',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgmznIfuB6lSriY6BjmusDzUUGHcT7wo_wog&s',
    7,
    'Nancy Ajram performs her greatest hits live.',
    2,
    '2025-11-05 20:00:00'
),
(
    'Tamer Hosny Festival',
    'https://scontent.fcai19-7.fna.fbcdn.net/v/t1.6435-9/46031636_2061172227272792_5288461190832324608_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=127cfc&_nc_eui2=AeF1y79jRl_lRyXE-_foMnJP3W3Mlxo1TvndbcyXGjVO-XUrHffbUukPUXq1cTTBofw&_nc_ohc=P-aXIRnl9CcQ7kNvwFp73EU&_nc_oc=AdmQrCr8PYcNPam_hUDlQj83kHp3O7WJzYUv3rssGy6Nc8i8q1orgjQgUiK9RqbWIzw&_nc_zt=23&_nc_ht=scontent.fcai19-7.fna&_nc_gid=ZKhm1BFxLixYeiHmmramOg&oh=00_AfUO0SXdU2OTsO9eIPkAe_B7nZBESaIuhjRgCOyp3AuSjw&oe=68BFBD5E',
    8,
    'Join Tamer Hosny for a festival of music and fun.',
    4,
    '2025-11-10 19:30:00'
),
(
    'Mohamed Mounir Tribute Concert',
    'https://mir-s3-cdn-cf.behance.net/projects/404/68de81177057611.64cfe90e76e24.jpg',
    9,
    'A tribute concert celebrating the music of Mohamed Mounir.',
    4,
    '2025-11-15 21:00:00'
);