CREATE TABLE ticket_category (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    event_id INT NOT NULL REFERENCES event(id)
);

INSERT INTO ticket_category (name, price, event_id) VALUES
('General Admission', 50.00, 1),
('VIP', 150.00, 1),
('Front Row', 200.00, 1),
('General Admission', 40.00, 2),
('VIP', 120.00, 2),
('Front Row', 180.00, 2),
('General Admission', 60.00, 3),
('VIP', 160.00, 3),
('Front Row', 220.00, 3),
('General Admission', 30.00, 4),
('VIP', 100.00, 4),
('Front Row', 150.00, 4),
('General Admission', 70.00, 5),
('VIP', 170.00, 5),
('Front Row', 250.00, 5),
('General Admission', 80.00, 6),
('VIP', 200.00, 6),
('Front Row', 300.00, 6);