CREATE TYPE ticket_status AS ENUM (
    'AVAILABLE',
    'RESERVED',
    'SOLD'
);

CREATE TABLE ticket(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_category_id INT NOT NULL REFERENCES ticket_category(id),
    name VARCHAR(255) NOT NULL,
    status ticket_status NOT NULL DEFAULT 'AVAILABLE',
    reserved_until TIMESTAMP,
    user_id INT REFERENCES users(id)
);

INSERT INTO ticket (ticket_category_id, name) VALUES
(1, 'Taylor Swift Concert - General Admission'),
(2, 'Taylor Swift Concert - VIP'),
(3, 'Taylor Swift Concert - Front Row'),
(4, 'Adele Live - General Admission'),
(5, 'Adele Live - VIP'),
(6, 'Adele Live - Front Row'),
(7, 'Beyoncé Homecoming - General Admission'),
(8, 'Beyoncé Homecoming - VIP'),
(9, 'Beyoncé Homecoming - Front Row'),
(10, 'Shakira Unplugged - General Admission'),
(11, 'Shakira Unplugged - VIP'),
(12, 'Shakira Unplugged - Front Row'),
(13, 'Amr Diab Hits Night - General Admission'),
(14, 'Amr Diab Hits Night - VIP'),
(15, 'Amr Diab Hits Night - Front Row'),
(16, 'Elissa Acoustic Session - General Admission'),
(17, 'Elissa Acoustic Session - VIP'),
(18, 'Elissa Acoustic Session - Front Row');